### ISSUE TITLE
"No authorization token" behind apache proxypass

### ISSUE THREAD

**Issue by krodelabestiole** [gesellix/keepass-node#9]
hello

thanks for the great tool i've been looking for for a while !
i've just installed all this on a lamp server that runs websites and such, and your app works perfectly locally.
but i'd rather use proxypass to have a nice url and already configured ssl than opening new ports on the server, router, etc.

```
# keepass-note
ProxyPass /keepass http://localhost:8443/keepass
ProxyPassReverse /keepass http://localhost:8443/keepass
<Proxy https://localhost:8443>
    Require all granted
</Proxy>
```
usually this setup works fine with node.js but here i run into this error : 
```
UnauthorizedError: No authorization token was found
   at middleware (/var/www/keepass-node/node_modules/express-jwt/lib/index.js:80:21)
   at /var/www/keepass-node/node_modules/express-unless/index.js:47:5
   at Layer.handle [as handle_request] (/var/www/keepass-node/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/var/www/keepass-node/node_modules/express/lib/router/index.js:312:13)
   at /var/www/keepass-node/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/keepass-node/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/keepass-node/node_modules/express/lib/router/index.js:271:10)
   at jsonParser (/var/www/keepass-node/node_modules/body-parser/lib/types/json.js:100:40)
   at Layer.handle [as handle_request] (/var/www/keepass-node/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/var/www/keepass-node/node_modules/express/lib/router/index.js:312:13)
```

i can't find any information on such an error. do you have any idea why this happens ?

**Comment by gesellix** [comment]
Hi @krodelabestiole :-)

I also didn't see that error, yet, but the reason is a missing `Authorization` header which is used to pass your credentials in a secure manner to the internal keepass reader.

Since you mentioned using the Apache `ProxyPass*` directives, I found some hints on StackOverflow. Apache seems to strip `Authorization` headers for security reasons. I won't be able to easily reproduce the issue on my host (I'm not an Apache user anymore), so I would just paste some links here which might be helpful for you. In essence they aim at telling the Apache _not_ to strip the required Authorization header:

- http://stackoverflow.com/questions/26549250/apache-strips-down-authorization-header?lq=1
- https://httpd.apache.org/docs/2.4/en/mod/core.html#cgipassauth

Please give the mentioned fixes a try and if something works for you, I'd be glad if you could write them down in this issue for other people with such problems. Thanks!

As a side note: I actually use the [HAProxy](http://www.haproxy.org/) for reverse proxying. You might consider using it instead of Apache.

**Comment by krodelabestiole** [comment]
@gesellix Thanks for your quick answer !
> write down your fix in a comment for other people with such problems

of course i would ! but i suspect the problem is a bit too tricky for me unfortunately...

I can't try **cgipassauth** yet because it requires apache 2.4.13 and jessie's latest apache version is only 2.4.10.
Anyway maybe my issue has more to do with the **proxy-chain-auth** directive for **[mod_proxy_http](http://httpd.apache.org/docs/2.4/mod/mod_proxy_http.html)**.
I found this topic which looks related : http://stackoverflow.com/questions/6213028/setting-up-mod-proxy-to-pass-http-authentication-to-server
But it doesn't change anything yet. Do you have any idea what value should I choose for **AuthType** None|Basic|Digest|Form ? And **[Auth(Basic)Provider](https://httpd.apache.org/docs/current/mod/mod_auth_basic.html#authbasicprovider)** ?
I tried a bit randomly the basic value combined to a basic auth in keepass-node config, and got another error :
`UnauthorizedError: Format is Authorization: Bearer [token]`

**Comment by gesellix** [comment]
There are different aspects to consider here:

- you can secure the access to keepass-node with a _basic_ authentication, which means that the browser will add an `Authorization: Basic ...` header to your requests. The _username_ and _password_ are entered in a browser's dialog box and are base64 encoded.
- the access to your keepass file needs the keepass password, though. That password is entered in the login form where you select your keepass kdbx file. Since that password is considered to be very important and shouldn't be easily readable by someone tampering with your connections, it's encoded as JWT payload. The JWT itself is be transmitted as `Authorization: Bearer ...` header.
- the `Proxy-Authorization` header is mostly necessary for corporate proxies where you need to authenticate at your proxy _and_ at the service behind it. So, you authorize yourself twice, at first at the proxy and then at a service (e.g. keepass). Both authorization header values are base64 encoded, so the headers usually start with `Authorization: Basic ...` and `Proxy-Authorization: Basic ...`. The proxy should remove the `Proxy-Authorization` header and only pass on the `Authorization` header to the service behind.

So regarding your question: I'd expect that the *proxy-chain-auth* directive would make sense for the last case, but won't help for the `Authorization: Bearer ...` token, which is the one making problems.

Did you try adding the following directives (to .htaccess) instead of `CGIPassAuth`?

    RewriteEngine On
    RewriteCond %{HTTP:Authorization} ^(.*)
    RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

Another snippet I've found was:

    SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

Essentially, they only seem to work with PHP, which recognizes `HTTP_AUTHORIZATION` as `AUTHORIZATION` header, but you might give it a try.

Sorry for only blindly providing some blind shots :-/

I'll try to reproduce your issue when time permits. If you have your Apache config/source online somewhere or if you could share something like a minimal example, I can give it a try without learning again how to configure the Apache correctly ;-)

**Comment by krodelabestiole** [comment]
here is my keepass.conf :

```
ProxyRequests Off
ProxyPreserveHost Off

# keepass-note
<Location /keepass>
    ProxyPass http://localhost:8443/keepass
    ProxyPassReverse http://localhost:8443/keepass
    AuthType basic
    AuthBasicAuthoritative Off
    SetEnv proxy-chain-auth On
    # SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
    AuthBasicFake username_set_in_keepass_node_config and_its_password
    # RewriteEngine On
    # RewriteCond %{HTTP:Authorization} ^(.*)
    # RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
    Require all granted
    #Require valid-user
</Location>
```

I have simplified a bit and removed every ssl related directive (i guess it has nothing to do with the issue)
i've tried to put the rewrite rules in the conf because i wouldn't know where to put the .htaccess (i guess apache is not using kp-node directory at all in that case). it's commented out because it doesn't change anything.
with this setup (authbasicfake) i get the Bearer [token] error, so i guess i'm a bit more advanced...

i think i will give up on this for now, for all this auth thing is a bit away from my understanding, despite your much appreciated explanations.
obviously i keep on following this thread and stay available for any suggestion or test.

**Comment by gesellix** [comment]
I'll give it a try to make it work with the Apache Httpd - but with low priority. Thanks for sharing your config!

If possible for you and if you only need a simple reverse proxy, I'd still suggest to give alternatives a try. I recommend https://caddyserver.com/ or http://www.haproxy.org/ - myself being a HAProxy user for the same use case like yourself. See https://github.com/gesellix/gesellix/blob/master/provisioning/roles/proxy/templates/haproxy.cfg.j2#L76 as an example.
